{% set name = "roocs-grids" %}
{% set package_name = "roocs_grids" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ package_name }}-{{ version }}.tar.gz
  sha256: 7dbf178314950b0c0160032412677141106701c38141d2481c0e622c7b3efed0

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - flit
  run:
    - python >=3.8

test:
  requires:
    - pip
  commands:
    - pip check 
  imports:
    - roocs_grids

about:
  home: https://github.com/roocs/roocs-grids/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A package containing grid descriptions for the roocs project
  dev_url: https://github.com/roocs/roocs-grids/

extra:
  recipe-maintainers:
    - sol1105 
    - cehbrecht
    - Zeitsperre
